name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: |
        & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -prerelease -latest -products * -requires Microsoft.VisualStudio.Component.VC.CMake.Project -property installationPath
